<a href="https://colab.research.google.com/github/Krish-8957/ML-Library-Practice/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
df=np.array([[1,2,3],
             [1,2,3]])
print(type(df))

<class 'numpy.ndarray'>


In [ ]:
dg=np.arange(1,11).reshape(-1,1)
print(dg)



[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [ ]:
df=np.linspace(1,10,30)
print(df)

[ 1.          1.31034483  1.62068966  1.93103448  2.24137931  2.55172414
  2.86206897  3.17241379  3.48275862  3.79310345  4.10344828  4.4137931
  4.72413793  5.03448276  5.34482759  5.65517241  5.96551724  6.27586207
  6.5862069   6.89655172  7.20689655  7.51724138  7.82758621  8.13793103
  8.44827586  8.75862069  9.06896552  9.37931034  9.68965517 10.        ]


In [ ]:
df=np.identity(3)
print(df)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#array attribute
df=np.array([1,2,3,4,5,6])
print(df.ndim)
print(df.shape)#rows and coloumn
print(df.size)
print(df.itemsize)#in bits
print(df.dtype)#use of astype
nf=df.astype(np.int32)
print(nf.dtype)

1
(6,)
6
8
int64
int32


In [ ]:
#array operation
df1=np.arange(0,12).reshape(3,4)
df2=np.arange(12,24).reshape(3,4)
print(df1*2)
print(df2==15)
print(df1+df2)
print(np.min(df1))
print(np.max(df1))
print(df1)
print(df2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[False False False  True]
 [False False False False]
 [False False False False]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
0
11
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame([[1,2],[3,4]])
df2 = pd.DataFrame([[5,6],[7,8]])
print(df1)
a = np.dot(df1, df2)
print(a)

   0  1
0  1  2
1  3  4
[[19 22]
 [43 50]]


In [ ]:
#array function
a1 = np.random.random((3, 3))
print(a1)
a1=np.round(a1*100)#return round figurejm
print(a1)

[[0.30869003 0.0088117  0.18309548]
 [0.66810069 0.54209858 0.66103959]
 [0.31824513 0.11729506 0.72176231]]
[[31.  1. 18.]
 [67. 54. 66.]
 [32. 12. 72.]]


In [ ]:
nf=np.arange(8).reshape(2,2,2)# 2 dimensional array
print(nf)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
#indexing and slicing
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
print(a1)
print(a2)
print(a1[-1])
# slicing
print(a1[2:5])
print(a2[:,0])
print(a2[0,:])
print(a2[1:,1:3])
print(a2[0:2,2:4])
print(a2[0:2,0::3])


[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
9
[2 3 4]
[0 4 8]
[0 1 2 3]
[[ 5  6]
 [ 9 10]]
[[2 3]
 [6 7]]
[[0 3]
 [4 7]]


In [ ]:
#for 3d
a3=np.arange(8).reshape(2,2,2)
print(a3)
print(a3[1,0,1])
#if we want 7
print(a3[1,1,1])
print(a3[1,0:1,0:])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5
7
[[4 5]]


In [ ]:
a4=np.arange(27).reshape(3,3,3)
print(a4)
print(a4[1,0::2,0::2])
print(a4[2,1:3,1:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[ 9 11]
 [15 17]]
[[22 23]
 [25 26]]
